wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710947744.31244
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 103
      3:
      - 2
      - 7
      - 23
      4: 3.9.16
      5: 0.16.3
      6: 4.37.1
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
