wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712489543.599633
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 103
      3:
      - 2
      - 7
      - 23
      4: 3.10.14
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: confusion_matrix._type
      5: 1
      6:
      - 1
    - 1: confusion_matrix.width
      5: 1
      6:
      - 1
    - 1: confusion_matrix.height
      5: 1
      6:
      - 1
    - 1: confusion_matrix.format
      5: 1
      6:
      - 1
    - 1: confusion_matrix.count
      5: 1
      6:
      - 1
    - 1: confusion_matrix.filenames
      5: 1
      6:
      - 1
    - 1: confusion_matrix.captions
      5: 1
      6:
      - 1
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
LEARNING_RATE:
  desc: null
  value: 0.0001
OUTPUT_SIZE:
  desc: null
  value: 1
